<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<h1>Upcoming Events &amp; News:</h1>
<h2>February 25, 2018 - Winterfest</h2>
<p>The 66th Annual Winter Festival is coming up on Sunday, February 25, 2018.  Come on down for a day of fun! There will be lots of stuff going on down at the club.  There are also tickets on sale for 25 different prizes and only 1,000 tickets are sold.  Check out the <a href="/EventsAndNews/Winterfest">Winter Festival</a> page for more information.</p>
<h2>April 2018 - Hunter Safety</h2>
<p>The club will be conducting their spring Hunter Education classes on April 18, 20, 25, 27 and May 2.  All classes will start at 6:00 PM and end at 9:00 PM.  All enrollments are done online.  Go to the Hunter Education page under EVENTS &amp; NEWS for more information</p>
<h1>Who we are...</h1>
<p>Welcome to the DePere Sportsmen’s Club! Established in 1952 by a group of dedicated volunteer sportsmen to further promote shooting sports in the Green Bay area, the De Pere Sportsmen's Club continues to provide opportunities for people of all ages to experience the benefits and beauty of a lovely natural surrounding while continuing to educate community members, and promote a wide range of shooting sports in a safe appropriate facility. The legacy of the founders continues today through the regular efforts of volunteers. Check in with a Board member to find out how you can help continue the legacy for future generations.</p>
<p>De Pere Sportsmen's Club offers a wide variety of leagues and annual events for you and your family, whether you are an experienced shooter, or a newbie looking for a place to learn and experience shooting sports. Do you have a son or daughter who would like to learn how to shoot? There are always experienced shooters both available and willing to help you with the basics, and steer you or your child into another Club opportunity. Emphasis is always placed on safety first to establish safe gun and bow handling habits. The De Pere Sportsmen's Club really takes an active interest in getting shooters started off right, and including them in the activities of the Club. De Pere Sportsmen's Club is proud of their collective role in bringing these fun sports to new generations of enthusiasts.</p>
<p>Whether you are interested in joining a league, shooting a few open rounds, or just grabbing a bowl of our famous chicken booyah at the festival, you'll surely find yourself at home at the De Pere Sportsmen's Club.</p>